### ISSUE TITLE
Pointer icon offset is not properly set

### ISSUE THREAD

**Issue by ahaasler** [vinceliuice/Vimix-cursors#1]
The pointer icon is not aligned with the default cursor.

![Screenshot from 2020-02-18 14-32-11](https://user-images.githubusercontent.com/1241721/74740876-0bffbe00-525c-11ea-84a6-152728b8353c.png)
![Screenshot from 2020-02-18 14-31-33](https://user-images.githubusercontent.com/1241721/74740882-0f934500-525c-11ea-9f55-dd22771d876b.png)

It should be placed a bit higher and to the right.

Tried this on Gnome 3.34.3 and Sway 1.2-rc1-48-ga085e649 on Arch Linux.

Thanks for this beautiful theme!

**Comment by vinceliuice** [comment]
OK, I'll fix this

**Comment by vinceliuice** [comment]
Fixed!

**Comment by ahaasler** [comment]
Did you push the changes?

**Comment by vinceliuice** [comment]
Oh! forgot about this, Now it's ok!
